### ISSUE TITLE
Is there a more convenient way to save the utf8 string? 

### ISSUE THREAD

**Issue by poerlang** [domske/stream-data-view#2]
StreamDataView is what i need，Well done @domske 。

I find StreamDataView  a little bit of a hassle to use （in save and read utf8）

see code below

```
const StreamDataView = require('stream-data-view').StreamDataView;
let stream = new StreamDataView();
stream.setNextInt32(123456);

//save utf8 string in to StreamDataView Obj
let str = 'Hello World. 你好世界。';
console.log(str,'StrLength:',str.length)
function getUtf8StrRealLength(str){
    var realLength = 0;
    var len = str.length;
    var charCode = -1;
    for(var i = 0; i < len; i++){
        charCode = str.charCodeAt(i);
        if (charCode >= 0 && charCode <= 128) {
            realLength += 1;
        }else{
            realLength += 3;
        }
    }
    return realLength;
}
let RealStrLength = getUtf8StrRealLength(str);
console.log(str,'RealStrLength:',RealStrLength)
stream.setNextInt32(RealStrLength);
stream.setNextString(str,true)


stream.setNextUint8(42);
// Get the byte data as pretty print.
console.log(stream.toByteString());

// Read any buffer.
let buffer = stream.getBuffer();
let read = new StreamDataView(buffer);

console.log('INT32 ', read.getNextInt32());


//read utf8 string from StreamDataView Obj
let utf8StrLen = read.getNextInt32();
console.log(utf8StrLen)
console.log('str ', read.getNextString(utf8StrLen,true));


console.log('UINT8 ', read.getNextUint8());
console.log(stream.toByteString());
```

**Comment by domske** [comment]
Thanks. Why not just use [setNextString(data, utf8, length)](https://domske.github.io/stream-data-view/#setnextstring-data-utf8-length)? This automatically handles UTF-8.

```js
const stream new StringDataView(100);
stream.setNextString('Hello World. 你好世界。', true);
console.log(stream.toByteString());
// 48 65 6C 6C 6F 20 57 6F 72 6C 64 2E 20 E4 BD A0 E5 A5 BD E4 B8 96 E7 95 8C E3 80 82
```

All string methods supports UTF-8 option. See [docs](https://domske.github.io/stream-data-view/). 
Note that UTF-8 string has different byte sizes. You can either create a new stream with the static method `fromTextString` and measure the byte length with `getLength`. Or set a fixed length to limit the string (crop) by the `length` option of string methods. Or handle it as you want. For example in your UI. Just keep in mind that the byte length of UTF-8 strings is variable, as a letter can be more than one byte long.

**Comment by domske** [comment]
Thanks. You can use [setNextString(data, utf8, length)](https://domske.github.io/stream-data-view/#setnextstring-data-utf8-length) and measure the length with [getLength](https://domske.github.io/stream-data-view/#getlength-) or limit the length.

```js
const stream new StringDataView();
stream.setNextString('Hello World. 你好世界。', true);
console.log(stream.toByteString(), `(${stream.getLength()})`);
// 48 65 6C 6C 6F 20 57 6F 72 6C 64 2E 20 E4 BD A0 E5 A5 BD E4 B8 96 E7 95 8C E3 80 82 (28)
```

Since UTF-8 string has different byte sizes. You can either create a new stream with the static method `fromTextString` and measure the byte length with `getLength`. Or set a fixed length to limit the string (crop) by the `length` option of string methods. Or handle it as you want. For example in your UI. Just keep in mind that the byte length of UTF-8 strings is variable, as a letter can be more than one byte long.

A solution from you example:

```js
const str = 'Hello World. 你好世界。';
const textStream = StreamDataView.fromTextString(str, true);
const stream = new StreamDataView();
stream.setNextInt32(123456);
stream.setNextInt32(textStream.getLength());

// Finally set the utf-8 string.
stream.setNextString(str, true);
// or set the bytes from the other stream.
stream.setNextBytes(textStream.getBuffer());
```
 
You can also suggest another solution. Ideas are always welcome.
